Rescue errors

diff --git a/bedsamplot b/bedsamplot
--- a/bedsamplot
+++ b/bedsamplot
@@ -110,17 +110,18 @@ while [[ ${#} -ge 1 ]]; do
 done
 
 
-echo '>> Print versions'
+echo '>>  Print versions'
 samplot --version
 python --version
 print_version
 
-echo '>> Run Samplot'
+echo '>>  Run Samplot'
 python -c "\
 from fileinput import input; \
-[(lambda a, b, c, d: print(f'-o ${PREFIX}.{a}_{b}_{c}_{d}.pdf -c {a} -s {b} -e {c}'))( \
+[(lambda a, b, c, d:
+  print(f'${SAMPLOT} plot -o ${PREFIX}.{a}_{b}_{c}_{d}.pdf -c {a} -s {b} -e {c} ${MAIN_ARGS[*]}'))( \
   *(lambda t: \
     (t[0], max(1, int(t[1]) + 1 - ${MARGIN}), int(t[2]) + ${MARGIN}, (t[3].replace(\";\", \"_\") if len(t) > 3 else \"\")) \
    )(s.split(maxsplit=4))) \
  for s in input()];" "${BED_PATH}" \
-  | xargs -P "${CPUS}" -I {} bash -xc "${SAMPLOT} plot {} ${MAIN_ARGS[*]}"
+  | xargs -P "${CPUS}" -I {} bash -c "{} && echo 'SUCCEEDED <-  {}' || echo 'FAILED    <-  {}'"
